# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    php_errors:
        log: true

    # Note that the session will be started ONLY if you read or write from it.

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        profiler:
            enabled: true
            collect: true
        session:
            enabled: true
            storage_factory_id: session.storage.factory.mock_file
