framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false

    property_info:
        with_constructor_extractor: true

    rate_limiter:
        login:
            policy: 'fixed_window'
            limit: 5
            interval: '15 minutes'

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true