twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/templates': ~
        '%kernel.project_dir%/vendor/doctrine/doctrine-migrations-bundle/templates': DoctrineMigrations

when@test:
    twig:
        strict_variables: true
