# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
security:
    # ...

    firewalls:
        main:
            # ...
            remember_me:
                secret:   '%kernel.secret%' # required
                lifetime: 604800 # 1 week in seconds
                # by default, the feature is enabled by checking a
                # checkbox in the login form (see below), uncomment the
                # following line to always enable it.
                #always_remember_me: true
                
parameters:
    stripe_webhook_secret: '%env(STRIPE_WEBHOOK_SECRET)%'

services:
    App\EventSubscriber\EntitySubscriber:
        arguments:
            $security: '@security.helper'
        tags:
            - { name: doctrine.event_subscriber }
    App\EventSubscriber\FormationsSubscriber:
        arguments:
            $formationRepository: '@App\Repository\FormationRepository'
            $twig: '@twig'
        tags:
            - { name: 'kernel.event_subscriber' }
    App\Service\StripeService:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'
    App\Service\PurchaseManager:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
    # default configuration for services in *this* file

    Symfony\Component\Validator\Validator\ValidatorInterface: '@validator'
    
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
